add_newline = false

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$openstack\
$kubernetes\
$gcloud\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

[character]
format = "$symbol "
success_symbol = "[>](fg:240)"
error_symbol = "[>](fg:240)"

[golang]
disabled = true

[directory]
truncate_to_repo = false
style = "bold fg:240"
format = "[$path]($style) "

[cmd_duration]
disabled = false
min_time = 0
format = "[$duration]($style)"
show_milliseconds = true
style = "fg:252"

[git_branch]
style = "bg:fg:242"
format = "[$branch]($style) "
disabled = false

[git_status]
disabled = true

[terraform]
format = "[$workspace]($style) "
disabled = false

[status]
style = "fg:242"
format = '[$status]($style)'
disabled = false

[gcloud]
disabled = true
format = '[$active]($style) '
style = "bold fg:250"

[python]
disabled = true

[nodejs]
disabled = true

[kubernetes]
disabled = false
style = "bold fg:252"
format = '[$context(\($namespace\))]($style) '
[[kubernetes.contexts]]
context_pattern = "gke_automatize-admin_europe-west2-a_etok-1"
context_alias = "gke"
[[kubernetes.contexts]]
context_pattern = "kind-kind"
context_alias = "kind"
